# http file with sample requests
# admin: Token 141da7beb2b023f9a4102fed942fb82f43e5eec7 
# user: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d


### user registration
POST http://localhost:8000/rest-auth/registration/
Content-Type: application/json

# HTTP/1.1 201 Created
# {
#   "key": "988abc86fa0421f59a37aae0863864c329ee5c34"
# }


### get user
GET http://localhost:8000/api/v1/users/3/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

# HTTP/1.1 200 OK


### edit user
PUT http://localhost:8000/api/v1/users/3/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

{
    "username": "Ivanych",
    "first_name": "Ivan",
    "last_name": "Ivanov",
    "email": "ivanov@yandex.ru",
    "company": "Home",
    "position": "director"
}

# HTTP/1.1 200 OK


### getting contacts
GET http://localhost:8000/api/v1/users/contact/
Content-Type: application/json
Authorization: Token 141da7beb2b023f9a4102fed942fb82f43e5eec7 

# HTTP/1.1 200 OK


### create contacts
POST http://localhost:8000/api/v1/users/contact/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

{
    "city": "Moscow",
    "street": "Dmitrovka",
    "house": "7",
    "structure": "-",
    "building": "1",
    "apartment": "11",
    "phone": "+7(903)1234567"
}

# HTTP/1.1 200 OK
# {
#   "Status": true
# }


### edit contact
PUT http://localhost:8000/api/v1/users/contact/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

{
    "id": "3",
    "city": "Moscow",
    "street": "Dmitrovka",
    "house": "7",
    "structure": "1",
    "building": "1",
    "apartment": "7",
    "phone": "+7(499)1274767"
}

# HTTP/1.1 200 OK
# {
#   "Status": true
# }


### delete contact
DELETE http://localhost:8000/api/v1/users/contact/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

{   
    "items": "3"
}

# HTTP/1.1 200 OK
# {
#   "Status": true,
#   "Deleted objects": 1
# }


### categories of products
GET http://localhost:8000/api/v1/categories/
Content-Type: application/json

# HTTP/1.1 200 OK


### shops list
GET http://localhost:8000/api/v1/shops
Content-Type: application/json

# HTTP/1.1 200 OK


### search for goods
GET http://localhost:8000/api/v1/products/?shop_id=2&category_id=224
Content-Type: application/json


### Products list
GET http://localhost:8000/api/v1/products/
Content-Type: application/json

# HTTP/1.1 200 OK
# []

### Receiving a basket
GET http://localhost:8000/api/v1/basket/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

# HTTP/1.1 200 OK
# []

### Receiving a orders
GET   http://localhost:8000/api/v1/order/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

# HTTP/1.1 200 OK

### update partner price list
POST http://localhost:8000/api/v1/partner/update/
Content-Type: application/x-www-form-urlencoded
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

{   
    "url": "https://raw.githubusercontent.com/netology-code/pd-diplom/master/data/shop1.yaml"
}

# HTTP/1.1 200 OK


### Get partner status
GET   http://localhost:8000/api/v1/partner/state/
Content-Type: application/json
Authorization: Token 2d41b8b3b897bd422882b07902b7d52c05a2a05d

# HTTP/1.1 200 OK